print("==================")
print("latihan 2 : Toko Mainan Anak")
print("==================")
namapembeli = input("masukan nama pembeli : ")
kodemainan = input("masukan kode mainan : ")
harga = int(input("masukan harga : "))
jumlahbeli = int(input("masukan jumlah beli : "))
print("==================")
print("nama pembeli = ", namapembeli)
print("masukan kode mainan = ", kodemainan)
print("masukan harga = ", harga)
print("masukan jumlah beli = ", jumlahbeli)
total = harga * jumlahbeli
print("Total         = ", total)